# Q3. Load the data from wine dataset. Check whether all attributes are standardized or not (mean is O and standard deviation is 1). If not, standardize the attributes. Do the same with Iris dataset.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dfwine = pd.read_csv('wine.csv')
dfwine.head()

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735

In [3]:
dfwine.describe()

Wine     Alcohol  Malic.acid         Ash         Acl          Mg  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     1.938202   13.000618    2.336348    2.366517   19.494944   99.741573   
std      0.775035    0.811827    1.117146    0.274344    3.339564   14.282484   
min      1.000000   11.030000    0.740000    1.360000   10.600000   70.000000   
25%      1.000000   12.362500    1.602500    2.210000   17.200000   88.000000   
50%      2.000000   13.050000    1.865000    2.360000   19.500000   98.000000   
75%      3.000000   13.677500    3.082500    2.557500   21.500000  107.000000   
max      3.000000   14.830000    5.800000    3.230000   30.000000  162.000000   

          Phenols  Flavanoids  Nonflavanoid.phenols     Proanth   Color.int  \
count  178.000000  178.000000            178.000000  178.000000  178.000000   
mean     2.295112    2.029270              0.361854    1.590899    5.058090   
std      0.625851    0.998859              0.124453    0.572359    2.318286   
min      0.980000    0.340000              0.130000    0.410000    1.280000   
25%      1.742500    1.205000              0.270000    1.250000    3.220000   
50%      2.355000    2.135000              0.340000    1.555000    4.690000   
75%      2.800000    2.875000              0.437500    1.950000    6.200000   
max      3.880000    5.080000              0.660000    3.580000   13.000000   

              Hue          OD      Proline  
count  178.000000  178.000000   178.000000  
mean     0.957449    2.611685   746.893258  
std      0.228572    0.709990   314.907474  
min      0.480000    1.270000   278.000000  
25%      0.782500    1.937500   500.500000  
50%      0.965000    2.780000   673.500000  
75%      1.120000    3.170000   985.000000  
max      1.710000    4.000000  1680.000000

In [4]:
dfiris = pd.read_csv('iris.csv')
dfiris.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [5]:
x = dfiris.iloc[:,:-1]

In [6]:
y = dfiris.iloc[:,-1]

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [8]:
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [9]:
#Standardizing Iris dataframe
std_s = StandardScaler() #making object of standard scaler
std_s.fit(x_train)
x_train_std = std_s.transform(x_train)
x_test_std = std_s.transform(x_test)

In [10]:
print(x_train[0:5])
print(x_train_std[0:5])
print(x_test[0:5])
print(x_test_std[0:5])

     sepal.length  sepal.width  petal.length  petal.width
37            4.9          3.6           1.4          0.1
119           6.0          2.2           5.0          1.5
2             4.7          3.2           1.3          0.2
90            5.5          2.6           4.4          1.2
115           6.4          3.2           5.3          2.3
[[-1.13738275  1.17665179 -1.2871855  -1.40332139]
 [ 0.15465273 -2.06928417  0.6763178   0.36397991]
 [-1.37229829  0.24924151 -1.34172726 -1.27708558]
 [-0.43263612 -1.1418739   0.34906725 -0.01472751]
 [ 0.62448381  0.24924151  0.83994308  1.37386637]]
    sepal.length  sepal.width  petal.length  petal.width
48           5.3          3.7           1.5          0.2
99           5.7          2.8           4.1          1.3
62           6.0          2.2           4.0          1.0
88           5.6          3.0           4.1          1.3
86           6.7          3.1           4.7          1.5
[[-0.66755166  1.40850435 -1.23264374 -1.27708558]
 [-

In [11]:
#Standardising all records of independent variable simultaneously
scaled_dfiris= std_s.fit_transform(x)
scaled_dfiris

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [12]:
 #Doing for wine DataFrame
xwine= dfwine.iloc[:,:-1]
ywine= dfwine.iloc[:,-1]

In [13]:
 xwine.values

array([[ 1.  , 14.23,  1.71, ...,  5.64,  1.04,  3.92],
       [ 1.  , 13.2 ,  1.78, ...,  4.38,  1.05,  3.4 ],
       [ 1.  , 13.16,  2.36, ...,  5.68,  1.03,  3.17],
       ...,
       [ 3.  , 13.27,  4.28, ..., 10.2 ,  0.59,  1.56],
       [ 3.  , 13.17,  2.59, ...,  9.3 ,  0.6 ,  1.62],
       [ 3.  , 14.13,  4.1 , ...,  9.2 ,  0.61,  1.6 ]])

In [14]:
 ywine.values

array([1065, 1050, 1185, 1480,  735, 1450, 1290, 1295, 1045, 1045, 1510,
       1280, 1320, 1150, 1547, 1310, 1280, 1130, 1680,  845,  780,  770,
       1035, 1015,  845,  830, 1195, 1285,  915, 1035, 1285, 1515,  990,
       1235, 1095,  920,  880, 1105, 1020,  760,  795, 1035, 1095,  680,
        885, 1080, 1065,  985, 1060, 1260, 1150, 1265, 1190, 1375, 1060,
       1120,  970, 1270, 1285,  520,  680,  450,  630,  420,  355,  678,
        502,  510,  750,  718,  870,  410,  472,  985,  886,  428,  392,
        500,  750,  463,  278,  714,  630,  515,  520,  450,  495,  562,
        680,  625,  480,  450,  495,  290,  345,  937,  625,  428,  660,
        406,  710,  562,  438,  415,  672,  315,  510,  488,  312,  680,
        562,  325,  607,  434,  385,  407,  495,  345,  372,  564,  625,
        465,  365,  380,  380,  378,  352,  466,  342,  580,  630,  530,
        560,  600,  650,  695,  720,  515,  580,  590,  600,  780,  520,
        550,  855,  830,  415,  625,  650,  550,  5

In [15]:
xwine_train,xwine_test, ywine_train, ywine_test = train_test_split(x,y,test_size=0.2)

In [16]:
# Standardising wine dataset
obj2 = StandardScaler() #making object
obj2.fit(xwine_train)
xwine_train_std = obj2.transform(xwine_train)
xwine_test_std = obj2.transform(xwine_test)

In [17]:
print(xwine_train[0:6]) 
print(xwine_train_std[0:6]) 
print(xwine_test[0:6]) 
print(xwine_test_std[0:6])

     sepal.length  sepal.width  petal.length  petal.width
60            5.0          2.0           3.5          1.0
19            5.1          3.8           1.5          0.3
124           6.7          3.3           5.7          2.1
31            5.4          3.4           1.5          0.4
18            5.7          3.8           1.7          0.3
74            6.4          2.9           4.3          1.3
[[-1.02528533 -2.31474197 -0.15148569 -0.26469614]
 [-0.90675523  1.60978131 -1.27014922 -1.16853663]
 [ 0.9897263   0.51963595  1.0790442   1.15562463]
 [-0.55116494  0.73766502 -1.27014922 -1.03941656]
 [-0.19557466  1.60978131 -1.15828287 -1.16853663]
 [ 0.63413601 -0.35248033  0.29597973  0.12266407]]
     sepal.length  sepal.width  petal.length  petal.width
57            4.9          2.4           3.3          1.0
28            5.2          3.4           1.4          0.2
58            6.6          2.9           4.6          1.3
44            5.1          3.8           1.9          0

In [18]:
#Standardising all records of independent variable simultaneously 
scaled_dfwine= obj2.fit_transform(xwine) 
scaled_dfwine

array([[-1.21394365,  1.51861254, -0.5622498 , ...,  0.25171685,
         0.36217728,  1.84791957],
       [-1.21394365,  0.24628963, -0.49941338, ..., -0.29332133,
         0.40605066,  1.1134493 ],
       [-1.21394365,  0.19687903,  0.02123125, ...,  0.26901965,
         0.31830389,  0.78858745],
       ...,
       [ 1.37386437,  0.33275817,  1.74474449, ...,  2.22423597,
        -1.61212515, -1.48544548],
       [ 1.37386437,  0.20923168,  0.22769377, ...,  1.83492299,
        -1.56825176, -1.40069891],
       [ 1.37386437,  1.39508604,  1.58316512, ...,  1.79166599,
        -1.52437837, -1.42894777]])